var univs = [
"University of Oxford",
"California Institute of Technology caltech",
"Massachusetts Institute of Technology",
"Princeton University",
"University of Chicago",
"ETH Zurich – Swiss Federal Institute of Technology Zurich",
"University of Pennsylvania",
"Johns Hopkins University",
"'University of California, Los Angeles'",
"University College London ucl",
"'University of California, Berkeley'",
"Northwestern University",
"National University of Singapore nus",
"Carnegie Mellon University",
"California Institute of Technology caltech",
"University of Washington",
"New York University",
"Tsinghua University Qinghua University Tsing hua University Qing hua University",
"'University of California, San Diego'",
"Georgia Institute of Technology",
"LMU Munich Ludwig-Maximilians-Universität München",
"King’s College London",
"École Polytechnique Fédérale de Lausanne",
"University of Hong Kong HKU hku The University of Hong Kong",
"Technical University of Munich",
"University of Wisconsin-Madison",
"Hong Kong University of Science and Technology hkust Hong Kong University of Science and Technology",
"Heidelberg University",
"Australian National University anu",
"Brown University",
"'Nanyang Technological University, Singapore  NTU Nan yang'",
"'University of California, Santa Barbara'",
"'University of California, Davis'",
"University of Minnesota",
"University of North Carolina at Chapel Hill",
"Chinese University of Hong Kong",
"Purdue University",
"Humboldt University of Berlin",
"Wageningen University & Research",
"University of Southern California",
"Utrecht University utrecht  utrecht university",
"'University of Maryland, College Park'",
"Ohio State University",
"Paris Sciences et Lettres – PSL Research University Paris",
"Kyoto University",
"University of Bristol",
"McMaster University",
"University of Glasgow",
"University of Groningen",
"University of New South Wales unsw australia unsw",
"Uppsala University",
"University of Helsinki",
"Technical University of Berlin",
"University of Tübingen",
"Korea Advanced Institute of Science and Technology (KAIST)",
"Durham University",
"'University of California, Irvine'",
"'versity of Colorado Boulder'''",
"Maastricht University",
"University of Bern",
"University of Montreal",
"University of Copenhagen",
"University of Western Australia uwa",
"University of Virginia",
"Indiana University",
"City University of Hong Kong CityU HK City U Hong Kong",
"Queen Mary University of London",
"Georgetown University",
"University of Mannheim",
"Charité - Universitätsmedizin Berlin",
"Université Catholique de Louvain",
"University of Geneva",
"Karlsruhe Institute of Technology",
"Stockholm University",
"Pohang University of Science and Technology postech",
"University of York",
"University of Birmingham",
"University of Florida",
"University of Cologne",
"Autonomous University of Barcelona",
"University of Sussex",
"University of Notre Dame",
"Technical University of Denmark",
"Scuola Superiore Sant’Anna",
"Case Western Reserve University",
"Texas A&M University",
"'University of California, Santa Cruz'",
"University of Erlangen-Nuremberg",
"Vrije Universiteit Amsterdam",
"University of Alabama at Birmingham",
"Tufts University",
"'Rutgers, the State University of New Jersey'",
"KTH Royal Institute of Technology",
"Université Libre de Bruxelles",
"University of Liverpool",
"Zhejiang University ZJU Zhejiang University China research",
"University of Luxembourg",
"Paris-Sud University",
"Hong Kong Polytechnic University hkpu hong kong poly",
"Scuola Normale Superiore di Pisa",
"University of Miami",
"University of East Anglia",
"Aalto University",
"University of Auckland",
"Lomonosov Moscow State University",
"Paris-Sorbonne University – Paris 4",
"'Royal Holloway, University of London'",
"'University of California, Riverside'",
"National Taiwan University",
"University of Cambridge",
"Stanford University",
"Harvard University",
"Imperial College London",
"KU Leuven",
"Pompeu Fabra University",
"Yale University",
"Columbia University",
"Ulm University",
"Duke University",
"Cornell University",
"University of Michigan",
"University of Toronto",
"University of Edinburgh",
"Peking University",
"University of Melbourne",
"University of British Columbia",
"University of Tokyo",
"University of Texas at Austin",
"Washington University in St Louis",
"McGill University",
"University of Illinois at Urbana-Champaign",
"Karolinska Institute",
"University of Amsterdam",
"University of Sydney",
"Delft University of Technology",
"University of Queensland",
"Leiden University",
"University of Manchester",
"Seoul National University",
"Pennsylvania State University",
"RWTH Aachen University",
"Monash University",
"Michigan State University",
"Rice University",
"Free University of Berlin",
"University of Warwick",
"Lund University",
"University of Basel",
"Emory University",
"University of Bonn",
"Boston University",
"Erasmus University Rotterdam",
"Radboud University Nijmegen",
"Pierre and Marie Curie University",
"Arizona State University",
"University of Southampton",
"University of Exeter",
"University of Science and Technology of China",
"University of Adelaide",
"University of Zurich",
"University of Leicester",
"University of Arizona",
"Cardiff University",
"University of Vienna",
"University of Würzburg",
"Nanjing University",
"University of Pittsburgh",
"University of Sheffield",
"Vanderbilt University",
"Aarhus University",
"Sungkyunkwan University (SKKU)",
"University of Göttingen",
"École Polytechnique",
"Trinity College Dublin",
"University of Leeds",
"Eindhoven University of Technology",
"University of St Andrews",
"University of Oslo",
"University of Nottingham",
"Lancaster University",
"University of Lausanne",
"University of Rochester",
"TU Dresden",
"University of Münster",
"Newcastle University",
"University of Cape Town",
"University of Aberdeen",
"University of Dundee",
"Shanghai Jiao Tong University",
"University of Massachusetts",
"Northeastern University",
"Tilburg University",
"University of Twente",
"École Normale Supérieure de Lyon",
"University of Gothenburg",
"University of Freiburg",
"Fudan University",
"University of Alberta",
"Dartmouth College",
"Ghent University"
]

let csv = ''
univs.forEach(function(univ, i) {
jQuery('input[placeholder="University search"]').val(univ).trigger('keyup')
csv += '"' + univ + '"' + ','+ '"'
  if (jQuery('table#qs-rankings tbody tr:first-child td:nth-child(1)').text() != "Oops... We couldn't find that university - please try searching again!") {
    csv += jQuery('table#qs-rankings tbody tr:first-child td:nth-child(2)').text()
  } else {
    csv += 'NaN'
  }

  csv += '"\n'
})
console.log(csv)
